.TH "data_read.f90" 3 "Tue Nov 8 2011" "I/O TOOLS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data_read.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBdata_readV_I\fP (pname, Y1)"
.br
.ti -1c
.RI "subroutine \fBdata_readV_R\fP (pname, Y1)"
.br
.ti -1c
.RI "subroutine \fBdata_readV_C\fP (pname, Y1)"
.br
.ti -1c
.RI "subroutine \fBdata_readM_I\fP (pname, Y1, X)"
.br
.ti -1c
.RI "subroutine \fBdata_readM_R\fP (pname, Y1, X)"
.br
.ti -1c
.RI "subroutine \fBdata_readM_C\fP (pname, Y1, X)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "subroutine data_readM_C (character(len=*)pname, complex(8),dimension(:,:)Y1, real(8),dimension(:),optionalX)"
.SS "subroutine data_readM_I (character(len=*)pname, integer,dimension(:,:)Y1, real(8),dimension(:),optionalX)"
.SS "subroutine data_readM_R (character(len=*)pname, real(8),dimension(:,:)Y1, real(8),dimension(:),optionalX)"
.SS "subroutine data_readV_C (character(len=*)pname, complex(8),dimension(:)Y1)"
.SS "subroutine data_readV_I (character(len=*)pname, integer,dimension(:)Y1)"
.SS "subroutine data_readV_R (character(len=*)pname, real(8),dimension(:)Y1)"
.SH "Author"
.PP 
Generated automatically by Doxygen for I/O TOOLS from the source code.
