.TH "IOTOOLS.f90" 3 "Tue Nov 8 2011" "I/O TOOLS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IOTOOLS.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBIOTOOLS\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBIOTOOLS::close_file\fP (pname)"
.br
.ti -1c
.RI "integer, public \fBIOTOOLS::file_size\fP (file, printf)"
.br
.ti -1c
.RI "integer, public \fBIOTOOLS::file_info\fP (file)"
.br
.ti -1c
.RI "integer, public \fBIOTOOLS::file_length\fP (file)"
.br
.ti -1c
.RI "function, public \fBIOTOOLS::reg_filename\fP (file)"
.br
.ti -1c
.RI "subroutine, public \fBIOTOOLS::data_store\fP (file, size)"
.br
.ti -1c
.RI "subroutine, public \fBIOTOOLS::data_open\fP (filename, tar)"
.br
.ti -1c
.RI "subroutine, public \fBIOTOOLS::create_data_dir\fP (dir_name)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, public \fBIOTOOLS::store_size\fP = 2048"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for I/O TOOLS from the source code.
