.TH "IPT_SOPT.f90" 3 "Tue Nov 8 2011" "Version 0.1" "IPT solution of DMFT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IPT_SOPT.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBIPT_SOPT\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "complex(8), dimension(-l:l), public \fBIPT_SOPT::solve_ipt_sopt\fP (fg0_, wr_)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "real(8), dimension(:), allocatable \fBIPT_SOPT::A0m\fP"
.br
.ti -1c
.RI "real(8), dimension(:), allocatable \fBIPT_SOPT::A0p\fP"
.br
.ti -1c
.RI "real(8), dimension(:), allocatable \fBIPT_SOPT::P1\fP"
.br
.ti -1c
.RI "real(8), dimension(:), allocatable \fBIPT_SOPT::P2\fP"
.br
.ti -1c
.RI "integer, dimension(:,:), allocatable \fBIPT_SOPT::iy_m_ix\fP"
.br
.ti -1c
.RI "integer, save \fBIPT_SOPT::loop\fP = 1"
.br
.ti -1c
.RI "complex(8), dimension(:), allocatable \fBIPT_SOPT::fg0\fP"
.br
.ti -1c
.RI "complex(8), dimension(:), allocatable \fBIPT_SOPT::sigma\fP"
.br
.ti -1c
.RI "real(8), dimension(:), allocatable \fBIPT_SOPT::wr\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for IPT solution of DMFT from the source code.
