.TH "IPT_ZEROT.f90" 3 "Tue Nov 8 2011" "Version 0.1" "IPT solution of DMFT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IPT_ZEROT.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBIPT_ZEROT\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "complex(8), dimension(-l:l), public \fBIPT_ZEROT::solve_ipt_zeroT\fP (fg0_, dw_, dt_)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, save \fBIPT_ZEROT::loop\fP = 1"
.br
.ti -1c
.RI "type(real_gf) \fBIPT_ZEROT::fg0\fP"
.br
.ti -1c
.RI "type(real_gf) \fBIPT_ZEROT::sigma\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for IPT solution of DMFT from the source code.
