.TH "IPT_SC_MATS.f90" 3 "Tue Nov 8 2011" "Version 0.1" "IPT solution of DMFT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IPT_SC_MATS.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBIPT_SC_MATS\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "complex(8), dimension(2, l), public \fBIPT_SC_MATS::solve_ipt_sc_matsubara\fP (fg0_, delta_)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, save \fBIPT_SC_MATS::loop\fP = 1"
.br
.ti -1c
.RI "type(matsubara_gf), dimension(2) \fBIPT_SC_MATS::fg0\fP"
.br
.ti -1c
.RI "type(matsubara_gf), dimension(2) \fBIPT_SC_MATS::sigma\fP"
.br
.ti -1c
.RI "type(matsubara_gf) \fBIPT_SC_MATS::calG11\fP"
.br
.ti -1c
.RI "type(matsubara_gf) \fBIPT_SC_MATS::calG22\fP"
.br
.ti -1c
.RI "type(matsubara_gf) \fBIPT_SC_MATS::calF\fP"
.br
.ti -1c
.RI "real(8) \fBIPT_SC_MATS::delta\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for IPT solution of DMFT from the source code.
