.TH "IPT_VARS_GLOBAL.f90" 3 "Tue Nov 8 2011" "Version 0.1" "IPT solution of DMFT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IPT_VARS_GLOBAL.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBIPT_VARS_GLOBAL\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBIPT_VARS_GLOBAL::read_input\fP (inputFILE)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer \fBIPT_VARS_GLOBAL::L\fP"
.br
.ti -1c
.RI "integer \fBIPT_VARS_GLOBAL::i\fP"
.br
.ti -1c
.RI "integer \fBIPT_VARS_GLOBAL::j\fP"
.br
.ti -1c
.RI "integer \fBIPT_VARS_GLOBAL::Nx\fP"
.br
.ti -1c
.RI "logical \fBIPT_VARS_GLOBAL::printf\fP"
.br
.ti -1c
.RI "real(8) \fBIPT_VARS_GLOBAL::wmin\fP"
.br
.ti -1c
.RI "real(8) \fBIPT_VARS_GLOBAL::wmax\fP"
.br
.ti -1c
.RI "real(8) \fBIPT_VARS_GLOBAL::eps_error\fP"
.br
.ti -1c
.RI "integer \fBIPT_VARS_GLOBAL::Nsuccess\fP"
.br
.ti -1c
.RI "real(8) \fBIPT_VARS_GLOBAL::weigth\fP"
.br
.ti -1c
.RI "real(8) \fBIPT_VARS_GLOBAL::deltasc\fP"
.br
.ti -1c
.RI "character(len=64) \fBIPT_VARS_GLOBAL::label\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for IPT solution of DMFT from the source code.
