.TH "MPT_MATS" 3 "Tue Nov 8 2011" "Version 0.1" "IPT solution of DMFT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MPT_MATS \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "complex(8), dimension(l), public \fBsolve_mpt_matsubara\fP (fg0_, n_, n0_, xmu0_)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, save \fBloop\fP = 1"
.br
.ti -1c
.RI "type(matsubara_gf) \fBfg0\fP"
.br
.ti -1c
.RI "type(matsubara_gf) \fBsigma\fP"
.br
.ti -1c
.RI "real(8) \fBn\fP"
.br
.ti -1c
.RI "real(8) \fBn0\fP"
.br
.ti -1c
.RI "real(8) \fBxmu0\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "complex(8),dimension(l),public MPT_MATS::solve_mpt_matsubara (complex(8),dimension(l)fg0_, real(8)n_, real(8)n0_, real(8)xmu0_)"
.PP
Definition at line 20 of file MPT_MATS.f90.
.SH "Variable Documentation"
.PP 
.SS "type(matsubara_gf) \fBMPT_MATS::fg0\fP"
.PP
Definition at line 11 of file MPT_MATS.f90.
.SS "integer,save \fBMPT_MATS::loop\fP = 1"
.PP
Definition at line 10 of file MPT_MATS.f90.
.SS "real(8) \fBMPT_MATS::n\fP"
.PP
Definition at line 12 of file MPT_MATS.f90.
.SS "real(8) \fBMPT_MATS::n0\fP"
.PP
Definition at line 12 of file MPT_MATS.f90.
.SS "type(matsubara_gf) \fBMPT_MATS::sigma\fP"
.PP
Definition at line 11 of file MPT_MATS.f90.
.SS "real(8) \fBMPT_MATS::xmu0\fP"
.PP
Definition at line 12 of file MPT_MATS.f90.
.SH "Author"
.PP 
Generated automatically by Doxygen for IPT solution of DMFT from the source code.
