.TH "sread_V.f90" 3 "Tue Nov 8 2011" "I/O TOOLS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sread_V.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBsreadV_II\fP (pname, X, Y1, Y2)"
.br
.ti -1c
.RI "subroutine \fBsreadV_IR\fP (pname, X, Y1, Y2)"
.br
.ti -1c
.RI "subroutine \fBsreadV_IC\fP (pname, X, Y1)"
.br
.ti -1c
.RI "subroutine \fBsreadV_RI\fP (pname, X, Y1, Y2)"
.br
.ti -1c
.RI "subroutine \fBsreadV_RR\fP (pname, X, Y1, Y2)"
.br
.ti -1c
.RI "subroutine \fBsreadV_RC\fP (pname, X, Y1)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "subroutine sreadV_IC (character(len=*)pname, integer,dimension(:)X, complex(8),dimension(:)Y1)"
.SS "subroutine sreadV_II (character(len=*)pname, integer,dimension(:)X, integer,dimension(:)Y1, integer,dimension(:),optionalY2)"
.SS "subroutine sreadV_IR (character(len=*)pname, integer,dimension(:)X, real(8),dimension(:)Y1, real(8),dimension(:),optionalY2)"
.SS "subroutine sreadV_RC (character(len=*)pname, real(8),dimension(:)X, complex(8),dimension(:)Y1)"
.SS "subroutine sreadV_RI (character(len=*)pname, real(8),dimension(:)X, integer,dimension(:)Y1, integer,dimension(:),optionalY2)"
.SS "subroutine sreadV_RR (character(len=*)pname, real(8),dimension(:)X, real(8),dimension(:)Y1, real(8),dimension(:),optionalY2)"
.SH "Author"
.PP 
Generated automatically by Doxygen for I/O TOOLS from the source code.
