FC=ifort
FFLAGS=-O2 -static-intel
MOPT=-module 
PLAT=intel
OBJ_DIR=/home/amaricci/projects_src/betaTESTcode/officina/SPLIT_SCIFOR_DMFT_TOOLS/dmft_tools/_install/src/intel_objs
MOD_DIR=/home/amaricci/projects_src/betaTESTcode/officina/SPLIT_SCIFOR_DMFT_TOOLS/dmft_tools/_install/src/intel_mods
LIB_DMFTT=/home/amaricci/projects_src/betaTESTcode/officina/SPLIT_SCIFOR_DMFT_TOOLS/dmft_tools/intel/lib/libdmftt.a
MOD_DMFTT=/home/amaricci/projects_src/betaTESTcode/officina/SPLIT_SCIFOR_DMFT_TOOLS/dmft_tools/intel/include
