.TH "IPT_SOPT" 3 "Tue Nov 8 2011" "Version 0.1" "IPT solution of DMFT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IPT_SOPT \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "complex(8), dimension(-l:l), public \fBsolve_ipt_sopt\fP (fg0_, wr_)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "real(8), dimension(:), allocatable \fBA0m\fP"
.br
.ti -1c
.RI "real(8), dimension(:), allocatable \fBA0p\fP"
.br
.ti -1c
.RI "real(8), dimension(:), allocatable \fBP1\fP"
.br
.ti -1c
.RI "real(8), dimension(:), allocatable \fBP2\fP"
.br
.ti -1c
.RI "integer, dimension(:,:), allocatable \fBiy_m_ix\fP"
.br
.ti -1c
.RI "integer, save \fBloop\fP = 1"
.br
.ti -1c
.RI "complex(8), dimension(:), allocatable \fBfg0\fP"
.br
.ti -1c
.RI "complex(8), dimension(:), allocatable \fBsigma\fP"
.br
.ti -1c
.RI "real(8), dimension(:), allocatable \fBwr\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "complex(8),dimension(-l:l),public IPT_SOPT::solve_ipt_sopt (complex(8),dimension(-l:l)fg0_, real(8),dimension(-l:l)wr_)"
.PP
Definition at line 25 of file IPT_SOPT.f90.
.SH "Variable Documentation"
.PP 
.SS "real(8),dimension(:),allocatable \fBIPT_SOPT::A0m\fP"
.PP
Definition at line 12 of file IPT_SOPT.f90.
.SS "real(8),dimension(:),allocatable \fBIPT_SOPT::A0p\fP"
.PP
Definition at line 12 of file IPT_SOPT.f90.
.SS "complex(8),dimension(:),allocatable \fBIPT_SOPT::fg0\fP"
.PP
Definition at line 15 of file IPT_SOPT.f90.
.SS "integer,dimension(:,:),allocatable \fBIPT_SOPT::iy_m_ix\fP"
.PP
Definition at line 13 of file IPT_SOPT.f90.
.SS "integer,save \fBIPT_SOPT::loop\fP = 1"
.PP
Definition at line 14 of file IPT_SOPT.f90.
.SS "real(8),dimension(:),allocatable \fBIPT_SOPT::P1\fP"
.PP
Definition at line 12 of file IPT_SOPT.f90.
.SS "real(8),dimension(:),allocatable \fBIPT_SOPT::P2\fP"
.PP
Definition at line 12 of file IPT_SOPT.f90.
.SS "complex(8),dimension(:),allocatable \fBIPT_SOPT::sigma\fP"
.PP
Definition at line 15 of file IPT_SOPT.f90.
.SS "real(8),dimension(:),allocatable \fBIPT_SOPT::wr\fP"
.PP
Definition at line 16 of file IPT_SOPT.f90.
.SH "Author"
.PP 
Generated automatically by Doxygen for IPT solution of DMFT from the source code.
