.TH "IPT_SC_MATS" 3 "Tue Nov 8 2011" "Version 0.1" "IPT solution of DMFT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IPT_SC_MATS \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "complex(8), dimension(2, l), public \fBsolve_ipt_sc_matsubara\fP (fg0_, delta_)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, save \fBloop\fP = 1"
.br
.ti -1c
.RI "type(matsubara_gf), dimension(2) \fBfg0\fP"
.br
.ti -1c
.RI "type(matsubara_gf), dimension(2) \fBsigma\fP"
.br
.ti -1c
.RI "type(matsubara_gf) \fBcalG11\fP"
.br
.ti -1c
.RI "type(matsubara_gf) \fBcalG22\fP"
.br
.ti -1c
.RI "type(matsubara_gf) \fBcalF\fP"
.br
.ti -1c
.RI "real(8) \fBdelta\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "complex(8),dimension(2,l),public IPT_SC_MATS::solve_ipt_sc_matsubara (complex(8),dimension(2,l)fg0_, real(8)delta_)"
.PP
Definition at line 21 of file IPT_SC_MATS.f90.
.SH "Variable Documentation"
.PP 
.SS "type(matsubara_gf) \fBIPT_SC_MATS::calF\fP"
.PP
Definition at line 12 of file IPT_SC_MATS.f90.
.SS "type(matsubara_gf) \fBIPT_SC_MATS::calG11\fP"
.PP
Definition at line 12 of file IPT_SC_MATS.f90.
.SS "type(matsubara_gf) \fBIPT_SC_MATS::calG22\fP"
.PP
Definition at line 12 of file IPT_SC_MATS.f90.
.SS "real(8) \fBIPT_SC_MATS::delta\fP"
.PP
Definition at line 13 of file IPT_SC_MATS.f90.
.SS "type(matsubara_gf),dimension(2) \fBIPT_SC_MATS::fg0\fP"
.PP
Definition at line 11 of file IPT_SC_MATS.f90.
.SS "integer,save \fBIPT_SC_MATS::loop\fP = 1"
.PP
Definition at line 10 of file IPT_SC_MATS.f90.
.SS "type(matsubara_gf),dimension(2) \fBIPT_SC_MATS::sigma\fP"
.PP
Definition at line 11 of file IPT_SC_MATS.f90.
.SH "Author"
.PP 
Generated automatically by Doxygen for IPT solution of DMFT from the source code.
