.TH "SLREAD.f90" 3 "Tue Nov 8 2011" "I/O TOOLS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SLREAD.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "interface \fBSLREAD::sread\fP"
.br
.in -1c
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBSLREAD\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "logical \fBSLREAD::control\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for I/O TOOLS from the source code.
