MODULE SCIFOR
  USE CONSTANTS
  USE MPI_VARS
  USE OMP_VARS
  USE FONTS
  USE TIMER
  ! #ifdef _FFT_MKL
  !   USE FFT_MKL
  ! #else
  USE FFT_FFTPACK
  ! #endif
  USE FUNCTIONS
  USE INTEGRATE
  USE IOTOOLS
  USE DERIVATE
  USE ARRAYS
  USE MATRIX
  USE RANDOM
  USE INTERPOLATE
  USE TOOLS
  USE STATISTICS
  USE OPTIMIZE
  USE SCIFOR_VERSION
  implicit none
END MODULE SCIFOR
