.TH "data_save.f90" 3 "Tue Nov 8 2011" "I/O TOOLS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data_save.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBdata_saveV_I\fP (pname, Y1)"
.br
.ti -1c
.RI "subroutine \fBdata_saveV_R\fP (pname, Y1)"
.br
.ti -1c
.RI "subroutine \fBdata_saveV_C\fP (pname, Y1)"
.br
.ti -1c
.RI "subroutine \fBdata_saveM_I\fP (pname, Y1, X)"
.br
.ti -1c
.RI "subroutine \fBdata_saveM_R\fP (pname, Y1, X)"
.br
.ti -1c
.RI "subroutine \fBdata_saveM_C\fP (pname, Y1, X)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "subroutine data_saveM_C (character(len=*)pname, complex(8),dimension(:,:)Y1, real(8),dimension(:),optionalX)"
.SS "subroutine data_saveM_I (character(len=*)pname, integer,dimension(:,:)Y1, real(8),dimension(:),optionalX)"
.SS "subroutine data_saveM_R (character(len=*)pname, real(8),dimension(:,:)Y1, real(8),dimension(:),optionalX)"
.SS "subroutine data_saveV_C (character(len=*)pname, complex(8),dimension(:)Y1)"
.SS "subroutine data_saveV_I (character(len=*)pname, integer,dimension(:)Y1)"
.SS "subroutine data_saveV_R (character(len=*)pname, real(8),dimension(:)Y1)"
.SH "Author"
.PP 
Generated automatically by Doxygen for I/O TOOLS from the source code.
