.TH "DMFT_IPT.f90" 3 "Tue Nov 8 2011" "Version 0.1" "IPT solution of DMFT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMFT_IPT.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBDMFT_IPT\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for IPT solution of DMFT from the source code.
