.TH "IOTOOLS" 3 "Tue Nov 8 2011" "I/O TOOLS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IOTOOLS \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBclose_file\fP (pname)"
.br
.ti -1c
.RI "integer, public \fBfile_size\fP (file, printf)"
.br
.ti -1c
.RI "integer, public \fBfile_info\fP (file)"
.br
.ti -1c
.RI "integer, public \fBfile_length\fP (file)"
.br
.ti -1c
.RI "function, public \fBreg_filename\fP (file)"
.br
.ti -1c
.RI "subroutine, public \fBdata_store\fP (file, size)"
.br
.ti -1c
.RI "subroutine, public \fBdata_open\fP (filename, tar)"
.br
.ti -1c
.RI "subroutine, public \fBcreate_data_dir\fP (dir_name)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, public \fBstore_size\fP = 2048"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine,public IOTOOLS::close_file (character(len=*)pname)"
.SS "subroutine,public IOTOOLS::create_data_dir (character(len=*),optionaldir_name)"
.SS "subroutine,public IOTOOLS::data_open (character(len=*)filename, logical,intent(out),optionaltar)"
.SS "subroutine,public IOTOOLS::data_store (character(len=*)file, integer,optionalsize)"
.SS "integer,public IOTOOLS::file_info (character(len=*)file)"
.SS "integer,public IOTOOLS::file_length (character(len=*)file)"
.SS "integer,public IOTOOLS::file_size (character(len=*)file, logical,optionalprintf)"
.SS "function,public IOTOOLS::reg_filename (character(len=*)file)"
.SH "Variable Documentation"
.PP 
.SS "integer,public \fBIOTOOLS::store_size\fP = 2048"
.SH "Author"
.PP 
Generated automatically by Doxygen for I/O TOOLS from the source code.
