.TH "IPT_MATS.f90" 3 "Tue Nov 8 2011" "Version 0.1" "IPT solution of DMFT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IPT_MATS.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBIPT_MATS\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "complex(8), dimension(-l:l), public \fBIPT_MATS::solve_ipt_matsubara\fP (fg0_)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, save \fBIPT_MATS::loop\fP = 1"
.br
.ti -1c
.RI "type(matsubara_gf) \fBIPT_MATS::fg0\fP"
.br
.ti -1c
.RI "type(matsubara_gf) \fBIPT_MATS::sigma\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for IPT solution of DMFT from the source code.
