.TH "IPT_ZEROT" 3 "Tue Nov 8 2011" "Version 0.1" "IPT solution of DMFT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IPT_ZEROT \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "complex(8), dimension(-l:l), public \fBsolve_ipt_zeroT\fP (fg0_, dw_, dt_)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, save \fBloop\fP = 1"
.br
.ti -1c
.RI "type(real_gf) \fBfg0\fP"
.br
.ti -1c
.RI "type(real_gf) \fBsigma\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "complex(8),dimension(-l:l),public IPT_ZEROT::solve_ipt_zeroT (complex(8),dimension(-l:l)fg0_, real(8)dw_, real(8)dt_)"
.PP
Definition at line 20 of file IPT_ZEROT.f90.
.SH "Variable Documentation"
.PP 
.SS "type(real_gf) \fBIPT_ZEROT::fg0\fP"
.PP
Definition at line 11 of file IPT_ZEROT.f90.
.SS "integer,save \fBIPT_ZEROT::loop\fP = 1"
.PP
Definition at line 10 of file IPT_ZEROT.f90.
.SS "type(real_gf) \fBIPT_ZEROT::sigma\fP"
.PP
Definition at line 11 of file IPT_ZEROT.f90.
.SH "Author"
.PP 
Generated automatically by Doxygen for IPT solution of DMFT from the source code.
