.TH "IPT_MATS" 3 "Tue Nov 8 2011" "Version 0.1" "IPT solution of DMFT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IPT_MATS \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "complex(8), dimension(-l:l), public \fBsolve_ipt_matsubara\fP (fg0_)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, save \fBloop\fP = 1"
.br
.ti -1c
.RI "type(matsubara_gf) \fBfg0\fP"
.br
.ti -1c
.RI "type(matsubara_gf) \fBsigma\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "complex(8),dimension(-l:l),public IPT_MATS::solve_ipt_matsubara (complex(8),dimension(-l:l)fg0_)"
.PP
Definition at line 23 of file IPT_MATS.f90.
.SH "Variable Documentation"
.PP 
.SS "type(matsubara_gf) \fBIPT_MATS::fg0\fP"
.PP
Definition at line 13 of file IPT_MATS.f90.
.SS "integer,save \fBIPT_MATS::loop\fP = 1"
.PP
Definition at line 12 of file IPT_MATS.f90.
.SS "type(matsubara_gf) \fBIPT_MATS::sigma\fP"
.PP
Definition at line 13 of file IPT_MATS.f90.
.SH "Author"
.PP 
Generated automatically by Doxygen for IPT solution of DMFT from the source code.
