.TH "IPT_KELDYSH.f90" 3 "Tue Nov 8 2011" "Version 0.1" "IPT solution of DMFT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IPT_KELDYSH.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBIPT_KELDYSH\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "complex(8), dimension(-l:l), public \fBIPT_KELDYSH::solve_ipt_keldysh\fP (fg0_, wr_, t_)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, save \fBIPT_KELDYSH::loop\fP = 1"
.br
.ti -1c
.RI "type(keldysh_equilibrium_gf) \fBIPT_KELDYSH::fg0\fP"
.br
.ti -1c
.RI "type(keldysh_equilibrium_gf) \fBIPT_KELDYSH::sigma\fP"
.br
.ti -1c
.RI "real(8), dimension(:), allocatable \fBIPT_KELDYSH::t\fP"
.br
.ti -1c
.RI "real(8), dimension(:), allocatable \fBIPT_KELDYSH::wr\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for IPT solution of DMFT from the source code.
