.TH "IPT_SC_SOPT.f90" 3 "Tue Nov 8 2011" "Version 0.1" "IPT solution of DMFT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IPT_SC_SOPT.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBIPT_SC_SOPT\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "complex(8), dimension(2,-l:l), public \fBIPT_SC_SOPT::solve_ipt_sc_sopt\fP (fg0_, wr_, delta_)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "real(8), dimension(:), allocatable \fBIPT_SC_SOPT::A0p11\fP"
.br
.ti -1c
.RI "real(8), dimension(:), allocatable \fBIPT_SC_SOPT::A0m11\fP"
.br
.ti -1c
.RI "real(8), dimension(:), allocatable \fBIPT_SC_SOPT::A0p22\fP"
.br
.ti -1c
.RI "real(8), dimension(:), allocatable \fBIPT_SC_SOPT::A0m22\fP"
.br
.ti -1c
.RI "real(8), dimension(:), allocatable \fBIPT_SC_SOPT::B0p\fP"
.br
.ti -1c
.RI "real(8), dimension(:), allocatable \fBIPT_SC_SOPT::B0m\fP"
.br
.ti -1c
.RI "real(8), dimension(:), allocatable \fBIPT_SC_SOPT::C0p\fP"
.br
.ti -1c
.RI "real(8), dimension(:), allocatable \fBIPT_SC_SOPT::C0m\fP"
.br
.ti -1c
.RI "real(8), dimension(:), allocatable \fBIPT_SC_SOPT::P1\fP"
.br
.ti -1c
.RI "real(8), dimension(:), allocatable \fBIPT_SC_SOPT::P2\fP"
.br
.ti -1c
.RI "real(8), dimension(:), allocatable \fBIPT_SC_SOPT::Q1\fP"
.br
.ti -1c
.RI "real(8), dimension(:), allocatable \fBIPT_SC_SOPT::Q2\fP"
.br
.ti -1c
.RI "real(8), dimension(:), allocatable \fBIPT_SC_SOPT::R1\fP"
.br
.ti -1c
.RI "real(8), dimension(:), allocatable \fBIPT_SC_SOPT::R2\fP"
.br
.ti -1c
.RI "real(8), dimension(:), allocatable \fBIPT_SC_SOPT::T1\fP"
.br
.ti -1c
.RI "real(8), dimension(:), allocatable \fBIPT_SC_SOPT::T2\fP"
.br
.ti -1c
.RI "real(8), dimension(:), allocatable \fBIPT_SC_SOPT::wr\fP"
.br
.ti -1c
.RI "integer, dimension(:,:), allocatable \fBIPT_SC_SOPT::iy_m_ix\fP"
.br
.ti -1c
.RI "integer, save \fBIPT_SC_SOPT::loop\fP = 1"
.br
.ti -1c
.RI "complex(8), dimension(:,:), allocatable \fBIPT_SC_SOPT::fg0\fP"
.br
.ti -1c
.RI "complex(8), dimension(:,:), allocatable \fBIPT_SC_SOPT::sigma\fP"
.br
.ti -1c
.RI "real(8) \fBIPT_SC_SOPT::delta\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for IPT solution of DMFT from the source code.
