.TH "MPT_MATS.f90" 3 "Tue Nov 8 2011" "Version 0.1" "IPT solution of DMFT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MPT_MATS.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBMPT_MATS\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "complex(8), dimension(l), public \fBMPT_MATS::solve_mpt_matsubara\fP (fg0_, n_, n0_, xmu0_)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, save \fBMPT_MATS::loop\fP = 1"
.br
.ti -1c
.RI "type(matsubara_gf) \fBMPT_MATS::fg0\fP"
.br
.ti -1c
.RI "type(matsubara_gf) \fBMPT_MATS::sigma\fP"
.br
.ti -1c
.RI "real(8) \fBMPT_MATS::n\fP"
.br
.ti -1c
.RI "real(8) \fBMPT_MATS::n0\fP"
.br
.ti -1c
.RI "real(8) \fBMPT_MATS::xmu0\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for IPT solution of DMFT from the source code.
