.TH "MPT_SOPT.f90" 3 "Tue Nov 8 2011" "Version 0.1" "IPT solution of DMFT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MPT_SOPT.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBMPT_SOPT\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "complex(8), dimension(-l:l), public \fBMPT_SOPT::solve_mpt_sopt\fP (fg0_, wr_, n_, n0_, xmu0_)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "real(8), dimension(:), allocatable \fBMPT_SOPT::A0m\fP"
.br
.ti -1c
.RI "real(8), dimension(:), allocatable \fBMPT_SOPT::A0p\fP"
.br
.ti -1c
.RI "real(8), dimension(:), allocatable \fBMPT_SOPT::P1\fP"
.br
.ti -1c
.RI "real(8), dimension(:), allocatable \fBMPT_SOPT::P2\fP"
.br
.ti -1c
.RI "integer, dimension(:,:), allocatable \fBMPT_SOPT::iy_m_ix\fP"
.br
.ti -1c
.RI "complex(8), dimension(:), allocatable \fBMPT_SOPT::fg0\fP"
.br
.ti -1c
.RI "complex(8), dimension(:), allocatable \fBMPT_SOPT::sigma\fP"
.br
.ti -1c
.RI "real(8), dimension(:), allocatable \fBMPT_SOPT::wr\fP"
.br
.ti -1c
.RI "real(8) \fBMPT_SOPT::n\fP"
.br
.ti -1c
.RI "real(8) \fBMPT_SOPT::n0\fP"
.br
.ti -1c
.RI "real(8) \fBMPT_SOPT::xmu0\fP"
.br
.ti -1c
.RI "integer, save \fBMPT_SOPT::loop\fP = 1"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for IPT solution of DMFT from the source code.
