.TH "SLREAD" 3 "Tue Nov 8 2011" "I/O TOOLS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SLREAD \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "interface \fBsread\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "logical \fBcontrol\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "logical \fBSLREAD::control\fP"
.SH "Author"
.PP 
Generated automatically by Doxygen for I/O TOOLS from the source code.
