.TH "splot_V.f90" 3 "Tue Nov 8 2011" "I/O TOOLS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
splot_V.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBsplotV_II\fP (pname, X, Y1, Y2, append)"
.br
.ti -1c
.RI "subroutine \fBsplotV_IR\fP (pname, X, Y1, Y2, append)"
.br
.ti -1c
.RI "subroutine \fBsplotV_IC\fP (pname, X, Y1, append)"
.br
.ti -1c
.RI "subroutine \fBsplotV_RI\fP (pname, X, Y1, Y2, append)"
.br
.ti -1c
.RI "subroutine \fBsplotV_RR\fP (pname, X, Y1, Y2, append)"
.br
.ti -1c
.RI "subroutine \fBsplotV_RC\fP (pname, X, Y1, append)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "subroutine splotV_IC (character(len=*)pname, integer,dimension(:)X, complex(8),dimension(:)Y1, logical,optionalappend)"
.SS "subroutine splotV_II (character(len=*)pname, integer,dimension(:)X, integer,dimension(:)Y1, integer,dimension(:),optionalY2, logical,optionalappend)"
.SS "subroutine splotV_IR (character(len=*)pname, integer,dimension(:)X, real(8),dimension(:)Y1, real(8),dimension(:),optionalY2, logical,optionalappend)"
.SS "subroutine splotV_RC (character(len=*)pname, real(8),dimension(:)X, complex(8),dimension(:)Y1, logical,optionalappend)"
.SS "subroutine splotV_RI (character(len=*)pname, real(8),dimension(:)X, integer,dimension(:)Y1, integer,dimension(:),optionalY2, logical,optionalappend)"
.SS "subroutine splotV_RR (character(len=*)pname, real(8),dimension(:)X, real(8),dimension(:)Y1, real(8),dimension(:),optionalY2, logical,optionalappend)"
.SH "Author"
.PP 
Generated automatically by Doxygen for I/O TOOLS from the source code.
