append_I – SciFortran
append_I Subroutine
18 statements
Source File
public subroutine append_I(vec, val)
Arguments
Type Intent Optional Attributes Name
integer, intent(inout), dimension(:), allocatable :: vec
integer, intent(in) :: val
Called by
Source Code
  subroutine append_I(vec,val)
    integer,dimension(:),allocatable,intent(inout) :: vec
    integer,intent(in)                             :: val
    integer,dimension(:),allocatable               :: tmp
    integer                                        :: n
    !
    if (allocated(vec)) then
       n = size(vec)
       allocate(tmp(n+1))
       tmp(:n) = vec
       call move_alloc(tmp,vec)
       n = n + 1
    else
       n = 1
       allocate(vec(n))
    end if
    !
    !Put val as last entry:
    vec(n) = val
    !
    if(allocated(tmp))deallocate(tmp)
  end subroutine append_I
Call graph
append calls append_i
dmatmul_csc_csc calls insert
dmatmul_csc_csr_2csc calls insert
dmatmul_csc_csr_2csr calls insert
dmatmul_csr_csr calls insert
zmatmul_csc_csc calls insert
zmatmul_csc_csr_2csc calls insert
zmatmul_csc_csr_2csr calls insert
zmatmul_csr_csr calls insert
matmul calls dmatmul_csc_csc, dmatmul_csc_csr_2csc, dmatmul_csc_csr_2csr, dmatmul_csr_csr, zmatmul_csc_csc, zmatmul_csc_csr_2csc, zmatmul_csc_csr_2csr, zmatmul_csr_csr