assert_eq2 – SciFortran
assert_eq2 Function
11 statements
Source File
public function assert_eq2(n1, n2, string)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n1
integer, intent(in) :: n2
character(len=*), intent(in) :: string
Return Value integer
Called by
Source Code
  function assert_eq2(n1,n2,string)
    character(len=*), intent(in)           :: string
    integer, intent(in)                    :: n1,n2
    integer                                :: assert_eq2
    if (n1 == n2) then
       assert_eq2=n1
    else
       write (*,*) 'nrerror: an assert_eq failed with this tag:', &
            string
       stop 'program terminated by assert_eq2'
    end if
  end function assert_eq2
Call graph
get_diag calls assert_eq2
put_diag calls assert_eq2
broyden1 calls get_diag, put_diag