assert_eq4 – SciFortran
assert_eq4 Function
11 statements
Source File
public function assert_eq4(n1, n2, n3, n4, string)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n1
integer, intent(in) :: n2
integer, intent(in) :: n3
integer, intent(in) :: n4
character(len=*), intent(in) :: string
Return Value integer
Called by
Source Code
  function assert_eq4(n1,n2,n3,n4,string)
    character(len=*), intent(in)           :: string
    integer, intent(in)                    :: n1,n2,n3,n4
    integer                                :: assert_eq4
    if (n1 == n2 .and. n2 == n3 .and. n3 == n4) then
       assert_eq4=n1
    else
       write (*,*) 'nrerror: an assert_eq failed with this tag:', &
            string
       stop 'program terminated by assert_eq4'
    end if
  end function assert_eq4
Call graph
fdjac calls assert_eq4
lnsrch calls assert_eq4
qrdcmp calls assert_eq4
qrupdt calls assert_eq4
rsolv calls assert_eq4
broyden1 calls fdjac, lnsrch, qrdcmp, qrupdt, rsolv