binary_search – SciFortran
binary_search Function
21 statements
Source File
public recursive function binary_search(Ain, value) result(bsresult)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: Ain(:)
integer, intent(in) :: value
Return Value integer
Calls
Called by
Source Code
  recursive function binary_search(Ain,value) result(bsresult)
    integer,intent(in)           :: Ain(:), value
    integer                      :: bsresult, mid
    integer,dimension(size(Ain)) :: A,Order
    !
    a = ain
    call sort_array(a,Order)
    !
    mid = size(a)/2 + 1
    if (size(a) == 0) then
       bsresult = 0        ! not found
       !stop "binary_search error: value not found"
    else if (a(mid) > value) then
       bsresult= binary_search(a(:mid-1), value)
    else if (a(mid) < value) then
       bsresult = binary_search(a(mid+1:size(a)), value)
       if (bsresult /= 0) then
          bsresult = mid + bsresult
       end if
    else
       bsresult = mid      ! SUCCESS !
    end if
    !
    bsresult = Order(bsresult)
    !
  end function binary_search
Call graph
binary_search calls binary_search, sort_array
dmatmul_csc_csc calls insert
dmatmul_csc_csr_2csc calls insert
dmatmul_csc_csr_2csr calls insert
dmatmul_csr_csr calls insert
zmatmul_csc_csc calls insert
zmatmul_csc_csr_2csc calls insert
zmatmul_csc_csr_2csr calls insert
zmatmul_csr_csr calls insert
matmul calls dmatmul_csc_csc, dmatmul_csc_csr_2csc, dmatmul_csc_csr_2csr, dmatmul_csr_csr, zmatmul_csc_csc, zmatmul_csc_csr_2csc, zmatmul_csc_csr_2csr, zmatmul_csr_csr