c_invert_tridiag_matrix_mat – SciFortran
c_invert_tridiag_matrix_mat Subroutine
14 statements
Source File
subroutine c_invert_tridiag_matrix_mat(Amat)
Arguments
Type Intent Optional Attributes Name
complex(kind=8), intent(inout), dimension(:,:) :: Amat
Calls
Source Code
subroutine c_invert_tridiag_matrix_mat(Amat)
  complex(8),dimension(:,:),intent(inout)         :: Amat
  complex(8),dimension(size(Amat,1))              :: diag_
  complex(8),dimension(size(Amat,1)-1)            :: sub_
  complex(8),dimension(size(Amat,1)-1)            :: over_
  complex(8),dimension(size(Amat,1))              :: Inv
  integer                                         :: i,N
  N=size(Amat,1)
  call assert_shape(Amat,[N,N],"d_invert_tridiag_matrix_mat","Amat")
  call get_tridiag(Amat,sub_,diag_,over_)
  call inv_tridiag(N,sub_,diag_,over_,Inv)
  Amat= dcmplx(0d0,0d0)
  forall(i=1:N)Amat(i,i)=Inv(i)
end subroutine c_invert_tridiag_matrix_mat
Call graph
c_invert_tridiag_matrix_mat calls assert_shape, get_tridiag, inv_tridiag