cfft_1d_ishift – SciFortran
cfft_1d_ishift Function
8 statements
Source File
public function cfft_1d_ishift(fin) result(fout)
Arguments
Type Intent Optional Attributes Name
complex(kind=8), dimension(:) :: fin
Return Value complex(kind=8), dimension(size(fin))
Called by
Source Code
  function cfft_1d_ishift(fin) result(fout)
    complex(8),dimension(:)          :: fin
    complex(8),dimension(size(fin))  :: fout
    integer                          :: L,p2
    L  = size(fin)
    p2 = L-floor(dble(L+1)/2.d0)
    fout = [fin(p2+1:),fin(1:p2)]
  end function cfft_1d_ishift
Call graph
ifftshift calls cfft_1d_ishift
c_itfft calls ifftshift
c_tfft calls ifftshift
d_itfft calls ifftshift
d_tfft calls ifftshift
itfft calls c_itfft, d_itfft
tfft calls c_tfft, d_tfft