chgu – SciFortran
chgu Subroutine
80 statements
Source File
public subroutine chgu(a, b, x, hu, md)
************80
! CHGU computes the confluent hypergeometric function U(a,b,x).
Licensing:
This routine is copyrighted by Shanjie Zhang and Jianming Jin.  However,
they give permission to incorporate this routine into a user program
provided that the copyright is acknowledged.
Modified:
27 July 2012
Author:
Shanjie Zhang, Jianming Jin
Reference:
Shanjie Zhang, Jianming Jin,
Computation of Special Functions,
Wiley, 1996,
ISBN: 0-471-11963-6,
LC: QA351.C45.
Parameters:
Input, real (kind = 8) A, B, parameters.
Input, real (kind = 8) X, the argument.
Output, real (kind = 8) HU, U(a,b,x).
Output, integer (kind = 4) MD, the method code.
Arguments
Type Intent Optional Attributes Name
real(kind=8) :: a
real(kind=8) :: b
real(kind=8) :: x
real(kind=8) :: hu
integer(kind=4) :: md
Calls
Call graph
chgu calls chgubi, chguit, chgul, chgus
chgubi calls gammaf, psi
chguit calls gammaf
chgus calls gammaf