d_itfft – SciFortran
d_itfft Subroutine
13 statements
Source File
public subroutine d_itfft(func_in, func_out)
Arguments
Type Intent Optional Attributes Name
real(kind=8), dimension(:) :: func_in
real(kind=8), optional, dimension(size(func_in)) :: func_out
Calls
Called by
Source Code
  subroutine d_itfft(func_in,func_out)
    real(8),dimension(:)                      :: func_in
    real(8),dimension(size(func_in)),optional :: func_out
    complex(8),dimension(size(func_in))          :: ftmp
    ftmp = func_in
    call ifft(ftmp)
    call fftex(ftmp)
    if(present(func_out))then
       func_out = ifftshift(ftmp)/size(ftmp)
    else
       func_in  = ifftshift(ftmp)/size(ftmp)
    endif
  end subroutine d_itfft
Call graph
d_itfft calls fftex, ifft, ifftshift
fftex calls cfft_1d_ex, rfft_1d_ex
ifft calls cfft_1d_backward, rfft_1d_backward
ifftshift calls cfft_1d_ishift, rfft_1d_ishift
cfft_1d_backward calls cfft1b, cfft1i
rfft_1d_backward calls rfft1b, rfft1i
itfft calls d_itfft