data_readV_I – SciFortran
data_readV_I Subroutine
21 statements
Source File
subroutine data_readV_I(pname, Y1)
Arguments
Type Intent Optional Attributes Name
character(len=*) :: pname
integer, dimension(:) :: Y1
Calls
Source Code
subroutine data_readV_I(pname,Y1)
  integer               :: i,Np
  character(len=*)      :: pname
  integer,dimension(:)  :: Y1
  Np=size(Y1)
  call data_open(trim(pname))
  include "ioread_control.f90"
  open(719,file=str(pname))
  do i=1,Np
     read(719,*)Y1(i)
  enddo
  close(719)
  call data_store(pname)
end subroutine data_readV_I
Call graph
data_readv_i calls data_open, data_store, str