data_readA3_C – SciFortran
data_readA3_C Subroutine
42 statements
Source File
subroutine data_readA3_C(pname, Y1, order, wspace)
Arguments
Type Intent Optional Attributes Name
character(len=*) :: pname
complex(kind=8), dimension(:,:,:) :: Y1
character(len=*), optional :: order
logical, optional :: wspace
Calls
Source Code
subroutine data_readA3_C(pname,Y1,order,wspace)
  integer                     :: Ny1,Ny2,Ny3
  integer                     :: i1,i2,i3
  character(len=*)            :: pname
  complex(8),dimension(:,:,:) :: Y1
  character(len=*),optional   :: order
  logical,optional            :: wspace
  character(len=1)            :: order_
  logical                     :: wspace_
  order_ = "R"   ; if(present(order))order_=trim(order(1:1))
  wspace_= .true.; if(present(wspace))wspace_=wspace
  !
  call file_gunzip(reg(pname))
  call ioread_control(pname,control)
  !
  open(free_unit(unit),file=reg(pname))
  !
  Ny1=size(Y1,1)
  Ny2=size(Y1,2)
  Ny3=size(Y1,3)
  !
  select case(order_)
  case default
     stop "read_array: order != Row-major, Col-major"
  case ("R")
     do i1=1,Ny1
        do i2=1,Ny2
           do i3=1,Ny3
              read(unit,*)Y1(i1,i2,i3)
           enddo
        enddo
     enddo
  case ("C")
     do i3=1,Ny3
        do i2=1,Ny2
           do i1=1,Ny1
              read(unit,*)Y1(i1,i2,i3)
           enddo
        enddo
     enddo
  end select
  close(unit)
  call file_gzip(reg(pname))
end subroutine data_readA3_C
Call graph
data_reada3_c calls file_gunzip, file_gzip, free_unit, ioread_control, reg