dmatmul_csc_csr_2csr – SciFortran
dmatmul_csc_csr_2csr Function
23 statements
Source File
public function dmatmul_csc_csr_2csr(A, B)
Arguments
Type Intent Optional Attributes Name
type(sparse_dmatrix_csc), intent(in) :: A
type(sparse_dmatrix_csr) :: B
Return Value real
Calls
Called by
Source Code
  function dmatmul_csc_csr_2csr(A,B) return(AxB)
    type(sparse_dmatrix_csc), intent(in) :: A
    type(sparse_dmatrix_csr)             :: B,AxB
    integer                              :: Na(2),Nb(2)
    integer                              :: icol,j,jrow,k,krow
    real(8)                              :: aval,bval
    Na = A%shape(); Nb = B%shape()
    if(Na(2)/=Nb(1))stop "Matrix not matching dimension in zmatmul_csc_csc"
    call AxB%free()
    call AxB%init(Na(1),Nb(2))
    do i=1,Na(2)
       do j=1,A%col(i)%Size
          jrow=A%col(i)%rows(j)
          aval=A%col(i)%vals(j)
          do k=1,B%row(i)%Size
             kcol=B%row(i)%cols(k)
             bval=B%row(i)%vals(k)
             AxB%insert(aval*bval,jrow,kcol)
          end do
       end do
    end do
  end function dmatmul_csc_csr_2csr
Call graph
dmatmul_csc_csr_2csr calls init, insert
append calls append_d, append_i, append_z
binary_search calls binary_search, sort_array
matmul calls dmatmul_csc_csr_2csr