dmatmul_csr_csr – SciFortran
dmatmul_csr_csr Function
23 statements
Source File
public function dmatmul_csr_csr(A, B)
Arguments
Type Intent Optional Attributes Name
type(sparse_dmatrix_csr), intent(in) :: A
type(sparse_dmatrix_csr), intent(in) :: B
Return Value real
Calls
Called by
Source Code
  function dmatmul_csr_csr(A,B) return(AxB)
    type(sparse_dmatrix_csr), intent(in) :: A,B
    type(sparse_dmatrix_csr)             :: AxB
    integer                              :: Na(2),Nb(2)
    integer                              :: irow,j,jcol,k,kcol
    real(8)                              :: aval,bval
    Na = A%shape(); Nb = B%shape()
    if(Na(2)/=Nb(1))stop "Matrix not matching dimension in dmatmul_csr_csr"
    call AxB%free()
    call AxB%init(Na(1),Nb(2))
    do irow=1,Na(1)
       do j=1,A%row(irow)%Size
          jcol=A%row(irow)%cols(j)
          aval=A%row(irow)%vals(j)
          do k=1,B%row(jcol)%Size
             kcol=B%row(jcol)%cols(k)
             bval=B%row(jcol)%vals(k)
             AxB%insert(aval*bval,irow,kcol)
          end do
       end do
    end do
  end function dmatmul_csr_csr
Call graph
dmatmul_csr_csr calls init, insert
append calls append_d, append_i, append_z
binary_search calls binary_search, sort_array
matmul calls dmatmul_csr_csr