dmatmul_csc_csr_2csc – SciFortran
dmatmul_csc_csr_2csc Function
23 statements
Source File
public function dmatmul_csc_csr_2csc(A, B)
Arguments
Type Intent Optional Attributes Name
type(sparse_dmatrix_csc), intent(in) :: A
type(sparse_dmatrix_csr) :: B
Return Value real
Calls
Called by
Call graph
dmatmul_csc_csr_2csc calls init, insert
append calls append_d, append_i, append_z
binary_search calls binary_search, sort_array
matmul calls dmatmul_csc_csr_2csc