dmatmul_csc_csc – SciFortran
dmatmul_csc_csc Function
23 statements
Source File
public function dmatmul_csc_csc(A, B)
Arguments
Type Intent Optional Attributes Name
type(sparse_dmatrix_csc), intent(in) :: A
type(sparse_dmatrix_csc), intent(in) :: B
Return Value real
Calls
Called by
Source Code
  function dmatmul_csc_csc(A,B) return(AxB)
    type(sparse_dmatrix_csc), intent(in) :: A,B
    type(sparse_dmatrix_csc)             :: AxB
    integer                              :: Na(2),Nb(2)
    integer                              :: icol,j,jrow,k,krow
    real(8)                              :: aval,bval
    Na = A%shape(); Nb = B%shape()
    if(Na(2)/=Nb(1))stop "Matrix not matching dimension in dmatmul_csc_csc"
    call AxB%free()
    call AxB%init(Na(1),Nb(2))
    do icol=1,Nb(2)
       do j=1,B%col(icol)%Size
          jrow=B%col(icol)%rows(j)
          bval=B%col(icol)%vals(j)
          do k=1,A%col(jrow)%Size
             krow=A%col(jrow)%rows(k)
             aval=A%col(jrow)%vals(k)
             AxB%insert(aval*bval,krow,icol)
          end do
       end do
    end do
  end function dmatmul_csc_csc
Call graph
dmatmul_csc_csc calls init, insert
append calls append_d, append_i, append_z
binary_search calls binary_search, sort_array
matmul calls dmatmul_csc_csc