ikv – SciFortran
ikv Subroutine
187 statements
Source File
public subroutine ikv(v, x, vm, bi, di, bk, dk)
************80
! IKV compute modified Bessel function Iv(x) and Kv(x) and their derivatives.
Licensing:
This routine is copyrighted by Shanjie Zhang and Jianming Jin.  However,
they give permission to incorporate this routine into a user program
provided that the copyright is acknowledged.
Modified:
17 July 2012
Author:
Shanjie Zhang, Jianming Jin
Reference:
Shanjie Zhang, Jianming Jin,
Computation of Special Functions,
Wiley, 1996,
ISBN: 0-471-11963-6,
LC: QA351.C45.
Parameters:
Input, real (kind = 8) V, the order of Iv(x) and Kv(x).
V = N + V0.
Input, real (kind = 8) X, the argument.
Output, real (kind = 8) VM, the highest order computed.
Output, real (kind = 8) BI(0:N), DI(0:N), BK(0:N), DK(0:N), the
values of In+v0(x), In+v0'(x), Kn+v0(x), Kn+v0'(x).
Arguments
Type Intent Optional Attributes Name
real(kind=8) :: v
real(kind=8) :: x
real(kind=8) :: vm
real(kind=8) :: bi(0:*)
real(kind=8) :: di(0:*)
real(kind=8) :: bk(0:*)
real(kind=8) :: dk(0:*)
Calls
Call graph
ikv calls gammaf, msta1, msta2
msta1 calls envj
msta2 calls envj