init_finter_c – SciFortran
init_finter_c Subroutine
16 statements
Source File
subroutine init_finter_c(func, xin, fin, N)
Arguments
Type Intent Optional Attributes Name
type(finter_type) :: func
real(kind=8) :: xin(:)
complex(kind=8) :: fin(size(xin))
integer :: N
Calls
Source Code
subroutine init_finter_c(func,Xin,Fin,N)
  type(finter_type) :: func
  real(8)           :: xin(:)
  complex(8)        :: fin(size(xin))
  integer           :: N,Lin
  if(func%status)call delete_finter(func)
  Lin=size(xin)
  allocate(func%x(Lin),func%f(Lin),func%g(Lin))
  func%X    = Xin
  func%F    = dreal(fin)
  func%G    = dimag(fin)
  func%Imax = Lin
  func%Imin = 1
  func%N    = N
  func%status=.true.
end subroutine init_finter_c
Call graph
init_finter_c calls delete_finter, dimag, f, g, x