jyna – SciFortran
jyna Subroutine
98 statements
Source File
public subroutine jyna(n, x, nm, bj, dj, by, dy)
************80
! JYNA computes Bessel functions Jn(x) and Yn(x) and derivatives.
Licensing:
This routine is copyrighted by Shanjie Zhang and Jianming Jin.  However,
they give permission to incorporate this routine into a user program
provided that the copyright is acknowledged.
Modified:
29 April 2012
Author:
Shanjie Zhang, Jianming Jin
Reference:
Shanjie Zhang, Jianming Jin,
Computation of Special Functions,
Wiley, 1996,
ISBN: 0-471-11963-6,
LC: QA351.C45.
Parameters:
Input, integer (kind = 4) N, the order.
Input, real (kind = 8) X, the argument.
Output, integer (kind = 4) NM, the highest order computed.
Output, real (kind = 8) BJ(0:N), DJ(0:N), BY(0:N), DY(0:N), the values
of Jn(x), Jn'(x), Yn(x), Yn'(x).
Arguments
Type Intent Optional Attributes Name
integer(kind=4) :: n
real(kind=8) :: x
integer(kind=4) :: nm
real(kind=8) :: bj(0:n)
real(kind=8) :: dj(0:n)
real(kind=8) :: by(0:n)
real(kind=8) :: dy(0:n)
Calls
Call graph
jyna calls jy01b, msta1, msta2
msta1 calls envj
msta2 calls envj