kmn – SciFortran
kmn Subroutine
142 statements
Source File
public subroutine kmn(m, n, c, cv, kd, df, dn, ck1, ck2)
************80
! KMN: expansion coefficients of prolate or oblate spheroidal functions.
Licensing:
This routine is copyrighted by Shanjie Zhang and Jianming Jin.  However,
they give permission to incorporate this routine into a user program
provided that the copyright is acknowledged.
Modified:
02 August 2012
Author:
Shanjie Zhang, Jianming Jin
Reference:
Shanjie Zhang, Jianming Jin,
Computation of Special Functions,
Wiley, 1996,
ISBN: 0-471-11963-6,
LC: QA351.C45.
Parameters:
Input, integer (kind = 4) M, the mode parameter;  M = 0, 1, 2, ...
Input, integer (kind = 4) N, mode parameter, N = M, M + 1, M + 2, ...
Input, real (kind = 8) C, spheroidal parameter.
Input, real (kind = 8) CV, the characteristic value.
Input, integer (kind = 4) KD, the function code.
1, the prolate function.
-1, the oblate function.
Input, real (kind = 8) DF(*), the expansion coefficients.
Arguments
Type Intent Optional Attributes Name
integer(kind=4) :: m
integer(kind=4) :: n
real(kind=8) :: c
real(kind=8) :: cv
integer(kind=4) :: kd
real(kind=8) :: df(200)
real(kind=8) :: dn(200)
real(kind=8) :: ck1
real(kind=8) :: ck2
Called by
Call graph
rmn2so calls kmn
rmn2sp calls kmn
rswfo calls rmn2so
rswfp calls rmn2sp