locate – SciFortran
locate Function
27 statements
Source File
public function locate(xx, x)
Arguments
Type Intent Optional Attributes Name
real(kind=8), intent(in), DIMENSION(:) :: xx
real(kind=8), intent(in) :: x
Return Value integer
Called by
Call graph
cinter calls locate
finter calls locate
finter2d calls locate