msta2 – SciFortran
msta2 Function
44 statements
Source File
public function msta2(x, n, mp)
************80
! MSTA2 determines a backward recurrence starting point for Jn(x).
Discussion:
This procedure determines the starting point for a backward
recurrence such that all Jn(x) has MP significant digits.
Licensing:
This routine is copyrighted by Shanjie Zhang and Jianming Jin.  However,
they give permission to incorporate this routine into a user program
provided that the copyright is acknowledged.
Modified:
08 July 2012
Author:
Shanjie Zhang, Jianming Jin
Reference:
Shanjie Zhang, Jianming Jin,
Computation of Special Functions,
Wiley, 1996,
ISBN: 0-471-11963-6,
LC: QA351.C45.
Parameters:
Input, real (kind = 8) X, the argument of Jn(x).
Input, integer (kind = 4) N, the order of Jn(x).
Input, integer (kind = 4) MP, the number of significant digits.
Output, integer (kind = 4) MSTA2, the starting point.
Arguments
Type Intent Optional Attributes Name
real(kind=8) :: x
integer(kind=4) :: n
integer(kind=4) :: mp
Return Value integer(kind=4)
Calls
Called by
Call graph
msta2 calls envj
cikna calls msta2
ciknb calls msta2
cikva calls msta2
cikvb calls msta2
cjyna calls msta2
cjynb calls msta2
cjyva calls msta2
cjyvb calls msta2
csphik calls msta2
csphjy calls msta2
ikna calls msta2
iknb calls msta2
ikv calls msta2
jyna calls msta2
jynb calls msta2
jyv calls msta2
lamn calls msta2
lamv calls msta2
rctj calls msta2
sphi calls msta2
sphj calls msta2
ch12n calls ciknb, cjynb
mtu12 calls jynb
rmn1 calls sphj
rmn2so calls rmn1
rswfo calls rmn1, rmn2so
rswfp calls rmn1