mtu12 – SciFortran
mtu12 Subroutine
132 statements
Source File
public subroutine mtu12(kf, kc, m, q, x, f1r, d1r, f2r, d2r)
************80
! MTU12 computes modified Mathieu functions of the first and second kind.
Discussion:
This procedure computes modified Mathieu functions of the first and
second kinds, Mcm(1)(2)(x,q) and Msm(1)(2)(x,q),
and their derivatives.
Licensing:
This routine is copyrighted by Shanjie Zhang and Jianming Jin.  However,
they give permission to incorporate this routine into a user program
provided that the copyright is acknowledged.
Modified:
31 July 2012
Author:
Shanjie Zhang, Jianming Jin
Reference:
Shanjie Zhang, Jianming Jin,
Computation of Special Functions,
Wiley, 1996,
ISBN: 0-471-11963-6,
LC: QA351.C45.
Parameters:
Input, integer (kind = 4) KF, the function code.
1 for computing Mcm(x,q);
2 for computing Msm(x,q).
Input, integer (kind = 4) KC, the function code.
1, for computing the first kind
2, for computing the second kind or Msm(2)(x,q) and Msm(2)'(x,q)
3, for computing both the first and second kinds.
Input, integer (kind = 4) M, the order of the Mathieu functions.
Input, real (kind = 8) Q, the parameter of the Mathieu functions.
Input, real (kind = 8) X, the argument of the Mathieu functions.
Output, real (kind = 8) F1R, D1R, F2R, D2R, the values of
Mcm(1)(x,q) or Msm(1)(x,q), Derivative of Mcm(1)(x,q) or Msm(1)(x,q),
Mcm(2)(x,q) or Msm(2)(x,q), Derivative of Mcm(2)(x,q) or Msm(2)(x,q).
Arguments
Type Intent Optional Attributes Name
integer(kind=4) :: kf
integer(kind=4) :: kc
integer(kind=4) :: m
real(kind=8) :: q
real(kind=8) :: x
real(kind=8) :: f1r
real(kind=8) :: d1r
real(kind=8) :: f2r
real(kind=8) :: d2r
Calls
Call graph
mtu12 calls cva2, fcoef, jynb
cva2 calls cv0, cvql, cvqm, refine
jynb calls msta1, msta2
cv0 calls cvql, cvqm
msta1 calls envj
msta2 calls envj
refine calls cvf