outerprod – SciFortran
outerprod Function
5 statements
Source File
public function outerprod(a, b) result(outerprod_d)
Arguments
Type Intent Optional Attributes Name
real(kind=8), intent(in), dimension(:) :: a
real(kind=8), intent(in), dimension(:) :: b
Return Value real(kind=8), dimension(size(a),size(b))
Called by
Source Code
  function outerprod(a,b) result(outerprod_d)
    real(8), dimension(:), intent(in)      :: a,b
    real(8), dimension(size(a),size(b))    :: outerprod_d
    outerprod_d = spread(a,dim=2,ncopies=size(b)) * &
         spread(b,dim=1,ncopies=size(a))
  end function outerprod
Call graph
broyden1 calls outerprod, qrdcmp
qrdcmp calls outerprod