pbdv – SciFortran
pbdv Subroutine
136 statements
Source File
public subroutine pbdv(v, x, dv, dp, pdf, pdd)
************80
! PBDV computes parabolic cylinder functions Dv(x) and derivatives.
Licensing:
This routine is copyrighted by Shanjie Zhang and Jianming Jin.  However,
they give permission to incorporate this routine into a user program
provided that the copyright is acknowledged.
Modified:
29 July 2012
Author:
Shanjie Zhang, Jianming Jin
Reference:
Shanjie Zhang, Jianming Jin,
Computation of Special Functions,
Wiley, 1996,
ISBN: 0-471-11963-6,
LC: QA351.C45.
Parameters:
Input, real (kind = 8) V, the order.
Input, real (kind = 8) X, the argument.
Output, real (kind = 8) DV(0:*), DP(0:*), the values of
Dn+v0(x), Dn+v0'(x).
Output, real (kind = 8) PDF, PDD, the values of Dv(x) and Dv'(x).
Arguments
Type Intent Optional Attributes Name
real(kind=8) :: v
real(kind=8) :: x
real(kind=8) :: dv(0:*)
real(kind=8) :: dp(0:*)
real(kind=8) :: pdf
real(kind=8) :: pdd
Calls
Call graph
pbdv calls dvla, dvsa
dvla calls gammaf, vvla
dvsa calls gammaf
vvla calls dvla, gammaf