pdf_print_pfile_1d – SciFortran
pdf_print_pfile_1d Subroutine
17 statements
Source File
subroutine pdf_print_pfile_1d(self, pfile, normalize)
Arguments
Type Intent Optional Attributes Name
type(pdf_kernel) :: self
character(len=*) :: pfile
logical, optional :: normalize
Calls
Source Code
subroutine pdf_print_pfile_1d(self,pfile,normalize)
  type(pdf_kernel) :: self
  character(len=*) :: pfile
  logical,optional :: normalize
  logical          :: normalize_
  integer          :: i,unit
  if(.not.self%status)stop "PDF_WRITE: PDF not allocated"
  normalize_ = .true.; if(present(normalize))normalize_=normalize
  if(normalize_)call pdf_normalize_1d(self)
  open(free_unit(unit),file=trim(pfile),access='append')
  do i=1,self%N
     write(unit,*)self%x(i),self%pdf(i)
  enddo
  write(unit,*)
  close(unit)
end subroutine pdf_print_pfile_1d
Call graph
pdf_print_pfile_1d calls free_unit, pdf, pdf_normalize_1d, x