psi – SciFortran
psi Subroutine
53 statements
Source File
public subroutine psi(x, ps)
************80
! PSI computes the PSI function.
Licensing:
The original FORTRAN77 version of this routine is copyrighted by
Shanjie Zhang and Jianming Jin.  However, they give permission to
incorporate this routine into a user program that the copyright
is acknowledged.
Modified:
08 September 2007
Author:
Original FORTRAN77 by Shanjie Zhang, Jianming Jin.
FORTRAN90 version by John Burkardt.
Reference:
Shanjie Zhang, Jianming Jin,
Computation of Special Functions,
Wiley, 1996,
ISBN: 0-471-11963-6,
LC: QA351.C45
Parameters:
Input, real (kind = 8) X, the argument.
Output, real (kind = 8) PS, the value of the PSI function.
Arguments
Type Intent Optional Attributes Name
real(kind=8) :: x
real(kind=8) :: ps
Called by
Call graph
chgubi calls psi
hygfx calls psi
hygfz calls psi
lpmv calls psi
chgu calls chgubi