random_exponential – SciFortran
random_exponential Function
10 statements
Source File
public function random_exponential() result(fn_val)
Arguments
None
Return Value real
Called by
Call graph
random_gamma calls random_exponential
random_poisson calls random_exponential
random_weibull calls random_exponential
random_chisq calls random_gamma