rfft_1d_shift – SciFortran
rfft_1d_shift Function
8 statements
Source File
public function rfft_1d_shift(fin) result(fout)
Arguments
Type Intent Optional Attributes Name
real(kind=8), dimension(:) :: fin
Return Value real(kind=8), dimension(size(fin))
Called by
Source Code
  function rfft_1d_shift(fin) result(fout)
    real(8),dimension(:)         :: fin
    real(8),dimension(size(fin)) :: fout
    integer                      :: L,p2
    L  = size(fin)
    p2 = floor(dble(L+1)/2.d0)
    fout = [fin(p2+1:),fin(1:p2)]
  end function rfft_1d_shift
Call graph
fftshift calls rfft_1d_shift
c_tfft calls fftshift
d_tfft calls fftshift
tfft calls c_tfft, d_tfft