rmn1 – SciFortran
rmn1 Subroutine
145 statements
Source File
public subroutine rmn1(m, n, c, x, df, kd, r1f, r1d)
************80
! RMN1 computes prolate and oblate spheroidal functions of the first kind.
Discussion:
This procedure computes prolate and oblate spheroidal radial
functions of the first kind for given m, n, c and x.
Licensing:
This routine is copyrighted by Shanjie Zhang and Jianming Jin.  However,
they give permission to incorporate this routine into a user program
provided that the copyright is acknowledged.
Modified:
29 July 2012
Author:
Shanjie Zhang, Jianming Jin
Reference:
Shanjie Zhang, Jianming Jin,
Computation of Special Functions,
Wiley, 1996,
ISBN: 0-471-11963-6,
LC: QA351.C45.
Parameters:
Input, integer (kind = 4) M, the mode parameter;  M = 0, 1, 2, ...
Input, integer (kind = 4) N, mode parameter, N = M, M + 1, M + 2, ...
Input, real (kind = 8) C, spheroidal parameter.
Input, real (kind = 8) X, the argument.
Input, real (kind = 8) DF(*), the expansion coefficients.
Input, integer (kind = 4) KD, the function code.
1, the prolate function.
-1, the oblate function.
Output, real (kind = 8) R1F, R1D, the function and derivative.
Arguments
Type Intent Optional Attributes Name
integer(kind=4) :: m
integer(kind=4) :: n
real(kind=8) :: c
real(kind=8) :: x
real(kind=8) :: df(200)
integer(kind=4) :: kd
real(kind=8) :: r1f
real(kind=8) :: r1d
Calls
Called by
Call graph
rmn1 calls sckb, sphj
sphj calls msta1, msta2
msta1 calls envj
msta2 calls envj
rmn2so calls rmn1
rswfo calls rmn1, rmn2so
rswfp calls rmn1