rmn2so – SciFortran
rmn2so Subroutine
75 statements
Source File
public subroutine rmn2so(m, n, c, x, cv, df, kd, r2f, r2d)
************80
! RMN2SO: oblate radial functions of the second kind with small argument.
Discussion:
This procedure computes oblate radial functions of the second kind
with a small argument, Rmn(-ic,ix) and Rmn'(-ic,ix).
Licensing:
This routine is copyrighted by Shanjie Zhang and Jianming Jin.  However,
they give permission to incorporate this routine into a user program
provided that the copyright is acknowledged.
Modified:
27 July 2012
Author:
Shanjie Zhang, Jianming Jin
Reference:
Shanjie Zhang, Jianming Jin,
Computation of Special Functions,
Wiley, 1996,
ISBN: 0-471-11963-6,
LC: QA351.C45.
Parameters:
Input, integer (kind = 4) M, the mode parameter;  M = 0, 1, 2, ...
Input, integer (kind = 4) N, mode parameter, N = M, M + 1, M + 2, ...
Input, real (kind = 8) C, spheroidal parameter.
Input, real (kind = 8) X, the argument.
Input, real (kind = 8) CV, the characteristic value.
Input, real (kind = 8) DF(*), the expansion coefficients.
Input, integer (kind = 4) KD, the function code.
1, the prolate function.
-1, the oblate function.
Output, real (kind = 8) R2F, R2D, the values of Rmn(-ic,ix)
and Rmn'(-ic,ix).
Arguments
Type Intent Optional Attributes Name
integer(kind=4) :: m
integer(kind=4) :: n
real(kind=8) :: c
real(kind=8) :: x
real(kind=8) :: cv
real(kind=8) :: df(200)
integer(kind=4) :: kd
real(kind=8) :: r2f
real(kind=8) :: r2d
Calls
Called by
Call graph
rmn2so calls gmn, kmn, qstar, rmn1, sckb
rmn1 calls sckb, sphj
sphj calls msta1, msta2
msta1 calls envj
msta2 calls envj
rswfo calls rmn2so