sdmn – SciFortran
sdmn Subroutine
153 statements
Source File
public subroutine sdmn(m, n, c, cv, kd, df)
************80
! SDMN: expansion coefficients for prolate and oblate spheroidal functions.
Licensing:
This routine is copyrighted by Shanjie Zhang and Jianming Jin.  However,
they give permission to incorporate this routine into a user program
provided that the copyright is acknowledged.
Modified:
29 July 2012
Author:
Shanjie Zhang, Jianming Jin
Reference:
Shanjie Zhang, Jianming Jin,
Computation of Special Functions,
Wiley, 1996,
ISBN: 0-471-11963-6,
LC: QA351.C45.
Parameters:
Input, integer (kind = 4) M, the mode parameter.
Input, integer (kind = 4) N, the mode parameter.
Input, real (kind = 8) C, the spheroidal parameter.
Input, real (kind = 8) CV, the characteristic value.
Input, integer (kind = 4) KD, the function code.
1, the prolate function.
-1, the oblate function.
Output, real (kind = 8) DF(*), expansion coefficients;
DF(1), DF(2), ... correspond to d0, d2, ... for even n-m and d1,
d3, ... for odd n-m
Arguments
Type Intent Optional Attributes Name
integer(kind=4) :: m
integer(kind=4) :: n
real(kind=8) :: c
real(kind=8) :: cv
integer(kind=4) :: kd
real(kind=8) :: df(200)
Called by
Call graph
aswfa calls sdmn
aswfb calls sdmn
rswfo calls sdmn
rswfp calls sdmn