sphj – SciFortran
sphj Subroutine
61 statements
Source File
public subroutine sphj(n, x, nm, sj, dj)
************80
! SPHJ computes spherical Bessel functions jn(x) and their derivatives.
Licensing:
This routine is copyrighted by Shanjie Zhang and Jianming Jin.  However,
they give permission to incorporate this routine into a user program
provided that the copyright is acknowledged.
Modified:
15 July 2012
Author:
Shanjie Zhang, Jianming Jin
Reference:
Shanjie Zhang, Jianming Jin,
Computation of Special Functions,
Wiley, 1996,
ISBN: 0-471-11963-6,
LC: QA351.C45.
Parameters:
Input, integer (kind = 4) N, the order.
Input, real (kind = 8) X, the argument.
Output, integer (kind = 4) NM, the highest order computed.
Output, real (kind = 8) SJ(0:N), the values of jn(x).
Output, real (kind = 8) DJ(0:N), the values of jn'(x).
Arguments
Type Intent Optional Attributes Name
integer(kind=4) :: n
real(kind=8) :: x
integer(kind=4) :: nm
real(kind=8) :: sj(0:n)
real(kind=8) :: dj(0:n)
Calls
Called by
Call graph
sphj calls msta1, msta2
msta1 calls envj
msta2 calls envj
rmn1 calls sphj
rmn2so calls rmn1
rswfo calls rmn1, rmn2so
rswfp calls rmn1