splotA3_RC – SciFortran
splotA3_RC Subroutine
29 statements
Source File
subroutine splotA3_RC(pname, X, Y1, append)
Arguments
Type Intent Optional Attributes Name
character(len=*) :: pname
real(kind=8), dimension(size(Y1,3)) :: X
complex(kind=8), dimension(:,:,:) :: Y1
logical, optional :: append
Calls
Source Code
subroutine splotA3_RC(pname,X,Y1,append)
  integer                       :: i,j,k,Ny1,Ny2,Ny3
  character(len=*)              :: pname
  complex(8),dimension(:,:,:)   :: Y1
  real(8),dimension(size(Y1,3)) :: X
  logical,optional              :: append
  logical                       :: check,append_
  append_=.false.;if(present(append))append_=append
  if(append_)then
     inquire(file=reg(pname),exist=check)
     open(free_unit(unit),file=reg(pname),position="append")
     if(check)write(unit,*)
  else
     open(free_unit(unit),file=reg(pname))
  endif
  !
  Ny1=size(Y1,1)
  Ny2=size(Y1,2)
  Ny3=size(Y1,3)
  !
  do i=1,Ny1
     do j=1,Ny2
        do k=1,Ny3
           write(unit,*)X(k),dimag(Y1(i,j,k)),dreal(Y1(i,j,k))
        enddo
        write(unit,*)""
     enddo
  enddo
  close(unit)
end subroutine splotA3_RC
Call graph
splota3_rc calls dimag, free_unit, reg