vvla – SciFortran
vvla Subroutine
38 statements
Source File
public subroutine vvla(va, x, pv)
************80
! VVLA computes parabolic cylinder function Vv(x) for large arguments.
Licensing:
This routine is copyrighted by Shanjie Zhang and Jianming Jin.  However,
they give permission to incorporate this routine into a user program
provided that the copyright is acknowledged.
Modified:
04 July 2012
Author:
Shanjie Zhang, Jianming Jin
Reference:
Shanjie Zhang, Jianming Jin,
Computation of Special Functions,
Wiley, 1996,
ISBN: 0-471-11963-6,
LC: QA351.C45.
Parameters:
Input, real (kind = 8) X, the argument.
Input, real (kind = 8) VA, the order nu.
Output, real (kind = 8) PV, the value of V(nu,x).
Arguments
Type Intent Optional Attributes Name
real(kind=8) :: va
real(kind=8) :: x
real(kind=8) :: pv
Calls
Called by
Call graph
vvla calls dvla, gammaf
dvla calls vvla, gammaf
pbvv calls vvla
pbdv calls dvla