wfun – SciFortran
wfun Function
111 statements
Source File
public function wfun(z)
Arguments
Type Intent Optional Attributes Name
complex(kind=8) :: z
Return Value complex(kind=8)
Calls
Source Code
  function wfun(z)
    complex(8):: z,wfun
    real(8)   :: x,y,u,v
    logical   :: flag
    x=real(z,8)
    y=aimag(z)
    call wofz(x,y,u,v,flag)
    wfun=cmplx(u,v)
  contains
    include "functions_wofz.f90"
  end function wfun
Call graph
wfun calls dcos, dexp, dsin, idint, idnint