cosft – SciFortran
cosft Interface
3 statements
Source File
public interface cosft
Calls
Module Procedures
public subroutine cost_1d_forward(func)
Arguments
Type Intent Optional Attributes Name
real(kind=8), intent(inout), dimension(:) :: func
Call graph
cosft calls cost_1d_forward
cost_1d_forward calls cost1f, cost1i