fft2 – SciFortran
fft2 Interface
3 statements
Source File
public interface fft2
Calls
Module Procedures
public subroutine rfft_2d_forward(func)
Arguments
Type Intent Optional Attributes Name
real(kind=8), intent(inout), dimension(:,:) :: func
public subroutine cfft_2d_forward(func)
Arguments
Type Intent Optional Attributes Name
complex(kind=8), intent(inout), dimension(:,:) :: func
Call graph
fft2 calls cfft_2d_forward, rfft_2d_forward
cfft_2d_forward calls cfft2f, cfft2i
rfft_2d_forward calls rfft2f, rfft2i