ifft – SciFortran
ifft Interface
3 statements
Source File
public interface ifft
Calls
Called by
Module Procedures
public subroutine rfft_1d_backward(func)
Arguments
Type Intent Optional Attributes Name
real(kind=8), intent(inout), dimension(:) :: func
public subroutine cfft_1d_backward(func)
Arguments
Type Intent Optional Attributes Name
complex(kind=8), intent(inout), dimension(:) :: func
Call graph
ifft calls cfft_1d_backward, rfft_1d_backward
cfft_1d_backward calls cfft1b, cfft1i
rfft_1d_backward calls rfft1b, rfft1i
c_itfft calls ifft
d_itfft calls ifft
itfft calls c_itfft, d_itfft