matmul – SciFortran
matmul Interface
10 statements
Source File
public interface matmul
Calls
Module Procedures
public function dmatmul_csr_csr(A, B)
Arguments
Type Intent Optional Attributes Name
type(sparse_dmatrix_csr), intent(in) :: A
type(sparse_dmatrix_csr), intent(in) :: B
Return Value real
public function zmatmul_csr_csr(A, B)
Arguments
Type Intent Optional Attributes Name
type(sparse_zmatrix_csr), intent(in) :: A
type(sparse_zmatrix_csr), intent(in) :: B
Return Value real
public function dmatmul_csc_csc(A, B)
Arguments
Type Intent Optional Attributes Name
type(sparse_dmatrix_csc), intent(in) :: A
type(sparse_dmatrix_csc), intent(in) :: B
Return Value real
public function zmatmul_csc_csc(A, B)
Arguments
Type Intent Optional Attributes Name
type(sparse_zmatrix_csc), intent(in) :: A
type(sparse_zmatrix_csc), intent(in) :: B
Return Value real
public function dmatmul_csc_csr_2csr(A, B)
Arguments
Type Intent Optional Attributes Name
type(sparse_dmatrix_csc), intent(in) :: A
type(sparse_dmatrix_csr) :: B
Return Value real
public function zmatmul_csc_csr_2csr(A, B)
Arguments
Type Intent Optional Attributes Name
type(sparse_zmatrix_csc), intent(in) :: A
type(sparse_zmatrix_csr) :: B
Return Value real
public function dmatmul_csc_csr_2csc(A, B)
Arguments
Type Intent Optional Attributes Name
type(sparse_dmatrix_csc), intent(in) :: A
type(sparse_dmatrix_csr) :: B
Return Value real
public function zmatmul_csc_csr_2csc(A, B)
Arguments
Type Intent Optional Attributes Name
type(sparse_zmatrix_csc), intent(in) :: A
type(sparse_zmatrix_csr) :: B
Return Value real
Call graph
matmul calls dmatmul_csc_csc, dmatmul_csc_csr_2csc, dmatmul_csc_csr_2csr, dmatmul_csr_csr, zmatmul_csc_csc, zmatmul_csc_csr_2csc, zmatmul_csc_csr_2csr, zmatmul_csr_csr
dmatmul_csc_csc calls init, insert
dmatmul_csc_csr_2csc calls init, insert
dmatmul_csc_csr_2csr calls init, insert
dmatmul_csr_csr calls init, insert
zmatmul_csc_csc calls init, insert
zmatmul_csc_csr_2csc calls init, insert
zmatmul_csc_csr_2csr calls init, insert
zmatmul_csr_csr calls init, insert
append calls append_d, append_i, append_z
binary_search calls binary_search, sort_array