sf_insert_element_coo – SciFortran
sf_insert_element_coo Interface
4 statements
Source File
public interface sf_insert_element_coo
Calls
Module Procedures
public subroutine sf_insert_delement_coo(sparse, value, i, j)
Arguments
Type Intent Optional Attributes Name
type(sf_sparse_dmatrix_coo), intent(inout) :: sparse
real(kind=8), intent(in) :: value
integer, intent(in) :: i
integer, intent(in) :: j
public subroutine sf_insert_celement_coo(sparse, value, i, j)
Arguments
Type Intent Optional Attributes Name
type(sf_sparse_cmatrix_coo), intent(inout) :: sparse
complex(kind=8), intent(in) :: value
integer, intent(in) :: i
integer, intent(in) :: j
Call graph
sf_insert_element_coo calls sf_insert_celement_coo, sf_insert_delement_coo
sf_insert_celement_coo calls add_to
sf_insert_delement_coo calls add_to