start_progress – SciFortran
start_progress Interface
3 statements
Source File
public interface start_progress
Calls
Module Procedures
public subroutine start_timer(title, unit)
Arguments
Type Intent Optional Attributes Name
character(len=*), optional :: title
integer, optional :: unit
Call graph
start_progress calls start_timer
start_timer calls mpi_wtime, check_mpi, get_rank_mpi
check_mpi calls mpi_initialized
get_rank_mpi calls mpi_comm_rank, error_mpi