#!/bin/bash
HERE=`pwd`
LIST=`ls -l |egrep '^d' |awk '{print $8}'`
EXCLUDED='wannab_lib LIBGPU NR man MKL*' 
for DIR in $EXCLUDED
do 
    LIST=`echo $LIST | sed "s/\b$DIR\b//g"`
done
echo $LIST > $HERE/file_to_sync
echo "sync the following dirs: $LIST"
rsync -avPhHz --delete  -e "ssh -l amaricci" $LIST 129.175.81.12:/home/amaricci/lib
rm $HERE/file_to_sync

