.TH FFTW 0 "<29 Sep 2010>" "" "FFTW module MAN PAGE"

.SH NAME
\fI FFTW\fP \- F95 library for Fast Fourier forward && backward Transformation

.SH CALL
In any fortran program: \fB use FFTW\fP

.SH DESCRIPTION

This page  explains how to use  \fB<FFTW>\fP module. 
The module contains  routines performing forward && backward Fast Fourier 
Transform of given 1-d arrays (2-d to come). Arrays contain function
of either real/imaginary (t, tau) time or real/Matsubara frequencies (w, iw_n).

.SS cfft_rw2rt
.SS cfft_rt2rw
.SS cfft_iw2tau
.SS cfft_tau2iw
.SS fft_iw2tau
.SS fft_tau2iw
.SS swap_fftrt2rw
.SS four1 





.SH ROUTINES

\fBCFFT_RW2RT\fP (F_IN(2*SIZE)[c],  F_OUT(-SIZE:SIZE)[c],  SIZE[i])

facciamo una prova


\fBCFFT_RT2RW\fP (F_IN(-SIZE:SIZE)[c], F_OUT(2*SIZE)[c], SIZE[i])



\fBCFFT_IW2TAU\fP (FW(:)[c],  FT(0:)[r],  BETA[r])



\fBCFFT_TAU2IW\fP (FT(0:)[r],  FW(:)[c],  BETA[r])



\fBFFT_IW2TAU\fP (FW(2*SIZE)[c],  FT(0:SIZE)[r], BETA[r],  SIZE[i])



\fBFFT_TAU2IW\fP (FT(0:SIZE)[r],  FW(2*SIZE)[c], BETA[r],  SIZE[i])



\fBFOUR1\fP (F(SIZE)[c],  SIZE[r],  SIGN[i])



\fBSWAP_FFTRT2RW\fP (F_IN(:)[c])

.SH NOTES ON COMPILATION:
