.TH GRIDS 0 "<28 Sep 2010>" "" "GRID module MAN PAGE"

.SH NAME
\fIGRIDS\fP \- F95 library for initialiazation of grids array

.SH CALL
In any fortran program: \fB use GRID\fP

.SH DESCRIPTION

This page  explains how to use  \fB<GRID>\fP module. 
The module contains some routines which goal is to 
initialize arrays storing  variables commonly used in 
any Condensed Matter program, e.g. Matsubara frequencies, 
real frequencies, real time, imaginary time, etc.

.SH ROUTINES

\fBINIT_WGRID\fP (ARRAY(:)[r],  minARRAY[r],  STEP[r] )

\fBINIT_EGRID\fP (ARRAY(:)[r],  minARRAY[r],  STEP[r] )

\fBINIT_WMGRID\fP (ARRAY(:)[r],  BETA[r] )

\fBINIT_TGRID\fP (ARRAY(-SIZE:SIZE)[r],  STEP[r],  SIZE[i])

\fBINIT_TAUGRID\fP (ARRAY(0:)[r],  STEP[r])


