MODULE SCIFOR
  USE SF_ARRAYS
  USE SF_CONSTANTS
  USE SF_DERIVATE
  ! #ifdef _FFT_MKL
  !   USE FFT_MKL
  ! #else
  USE SF_FFT_FFTPACK
  ! #endif
  USE SF_FONTS
  USE SF_INTEGRATE
  USE SF_INTERPOLATE
  USE SF_IOTOOLS
  USE SF_LINALG
  USE SF_MISC
  USE SF_OPTIMIZE
  USE SF_RANDOM
  USE SF_SPECIAL
  USE SF_STAT
  USE SF_TIMER
  USE SCIFOR_VERSION
  implicit none
END MODULE SCIFOR
