.TH COMMON_VARS 0 "<19 Oct 2010>" "" "COMMON_VARS module MAN PAGE"

.SH NAME
\fICOMMON_VARS\fP \- F95 library containing common variables

.SH CALL
In any fortran program: \fB use COMMON_VARS\fP

.SH DESCRIPTION

This page  explains how to use  \fB<COMMON_VARS>\fP module. 
The module contains the definition of many commonly used variables 
and parameters, like e.g. PI,EULER,SQRT(2),etc..
The goal is to simplify the writing of new codes by including 
general variables from here. 

.SH VARIABLES

\fBCOMPLEX PARAMETERS\fP
  ZERO=(0.D0,0.D0) , XI=(0.D0,1.D0) , ONE=(1.D0,0.D0)

\fBREAL PARAMETERS\fP
  SQRT2 = 1.414213...
  SQRT3 = 1.732050...
  SQRT6 = 2.449489...
  PI    = 3.141592...
  PI2   = 6.283185...
  GAMMA_EULER = 0.577215664...
  EULER= 2.7182818...
  MAX_REAL = HUGE(1.D0)
  MAX_EXP  =  700.D0 , MIN_EXP  = -700.D0
  MAX_EXP_QUAD = 11000.D0 , MIN_EXP_QUAD =-11000.D0
  MAX_EXP_R =  81.D0 , MIN_EXP_R = -81.D0
  ERROR=EPSILON(1.D0)*100.D0
  EPSILONR=EPSILON(1.D0),EPSILONQ=1.D-30
  TINY_   = 1.D-12
  HUGE_   = 1.D+12
  QUARTER = 0.25_DBL
  THIRD   = 0.3333333333333_DBL
  HALF    = 0.5_DBL

\fBINTEGER  PARAMETERS\fP
  MAX_INT  = HUGE(1)  
  DBL=8,DP=8 "DOUBLE" PRECISION
  DDP=16     "QUAD"   PRECISION
  SP = KIND(1.0) "SINGLE" PRECISION

\fBLOGICAL  PARAMETERS\fP
  TT=.TRUE., FF=.FALSE.

\fBGLOBAL  VARIABLES\fP
  iloop,nloop    !DMFT loop variables
  D              !Bandwidth
  ts,tsp         !n.n./n.n.n. hopping amplitude
  U,V            !local,non-local interaction
  tpd,Vpd        !Hybridization,band-band coupling
  xmu            !chemical potential
  dt,dtau        !time step
  fmesh          !freq. step
  de             !energy step
  beta           !inverse temp
  eps            !broadening


\fBMPI  VARIABLES\fP
  mpiERR,mpiSIZE,mpiID
