.\"Created with GNOME Manpages Editor
.\"http://sourceforge.net/projects/gmanedit2

.\"Replace <program> with the program name, x with the Section Number
.TH <GRID> 0 "<28 Sep 2010>" "" "GRID module MAN PAGE"

.SH NAME
<GRID> \- F95 library for initialiazation of grids array

.SH CALL
In any fortran program:
.B use GRID
.RI 
.br

.SH DESCRIPTION

This page  explains how to use  \fB<GRID>\fP module. 
The module contains some routines which goal is to initialize arrays storing   variables commonly used in any Condensed Matter program, e.g. Matsubara frequencies, real frequencies, real time, imaginary time, etc.

.SH ROUTINES
  \fB<init_wgrid>\fB (ARRAY, minVALUE, STEP)

  \fB<init_egrid>\fB (ARRAY, minVALUE, STEP)

  \fB<init_wmgrid>\fB (ARRAY, BETA)
 
  \fB<init_tgrid>\fB (ARRAY, STEP, ARRAY_SIZE)

  \fB<init_taugrid>\fB (ARRAY, STEP)

.SH SYNOPSIS

.SH NOTES



